#!/usr/bin/env python3
"""Recompute LoRA vs HL-Residual metrics after excluding a diagnostic pilot subset."""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np
import pandas as pd

METRICS = ["mIoU", "F1", "Boundary_IoU"]
DEFAULT_LORA = "Prompt-free LoRA"
DEFAULT_HL = "HL-Residual (Ours)"
LB = r"\\"

def load_pilot_names(path: Path | None) -> set[str]:
    if path is None:
        return set()
    if not path.exists():
        raise FileNotFoundError(f"Pilot manifest not found: {path}")
    names = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            names.add(Path(line).stem)
    return names

def bootstrap_ci(values: np.ndarray, n_boot: int = 2000, seed: int = 123) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    means = np.empty(n_boot, dtype=float)
    n = len(values)
    for i in range(n_boot):
        means[i] = rng.choice(values, size=n, replace=True).mean()
    lo, hi = np.percentile(means, [2.5, 97.5])
    return float(lo), float(hi)

def fmt(x: float) -> str:
    return f"{x:.2f}"

def make_latex_tables(per_seed: pd.DataFrame, paired: pd.DataFrame, out: Path) -> None:
    lines = []
    lines += [
        "% Auto-generated by recompute_excluding_pilot_metrics.py",
        "\\begin{table}[H]",
        "\\caption{Main Results After Excluding the Diagnostic Pilot Subset}",
        "\\label{tab:excluding_pilot_main_results}",
        "\\centering",
        "\\small",
        "\\begin{tabular}{c l c c c c c}",
        "\\toprule",
        rf"\textbf{{Seed}} & \textbf{{Method}} & \textbf{{mIoU (\%)}} & \textbf{{F1 (\%)}} & \textbf{{BIoU (\%)}} & \textbf{{$\Delta$ mIoU}} & \textbf{{$\Delta$ BIoU}} {LB}",
        "\\midrule",
    ]
    for seed, sub in per_seed.groupby("seed", sort=True):
        lora = sub[sub["model"] == DEFAULT_LORA].iloc[0]
        hl = sub[sub["model"] == DEFAULT_HL].iloc[0]
        lines.append(rf"\multirow{{2}}{{*}}{{{seed}}} & LoRA & {fmt(lora.mIoU_pct)} & {fmt(lora.F1_pct)} & {fmt(lora.Boundary_IoU_pct)} & -- & -- {LB}")
        lines.append(rf" & HL-Residual & \textbf{{{fmt(hl.mIoU_pct)}}} & \textbf{{{fmt(hl.F1_pct)}}} & \textbf{{{fmt(hl.Boundary_IoU_pct)}}} & {fmt(hl.mIoU_pct-lora.mIoU_pct)} & {fmt(hl.Boundary_IoU_pct-lora.Boundary_IoU_pct)} {LB}")
        lines.append("\\midrule")
    mean = per_seed.groupby("model")[["mIoU_pct", "F1_pct", "Boundary_IoU_pct"]].mean().reset_index()
    lora = mean[mean["model"] == DEFAULT_LORA].iloc[0]
    hl = mean[mean["model"] == DEFAULT_HL].iloc[0]
    lines.append(rf"\multirow{{2}}{{*}}{{Mean}} & LoRA & {fmt(lora.mIoU_pct)} & {fmt(lora.F1_pct)} & {fmt(lora.Boundary_IoU_pct)} & -- & -- {LB}")
    lines.append(rf" & HL-Residual & \textbf{{{fmt(hl.mIoU_pct)}}} & \textbf{{{fmt(hl.F1_pct)}}} & \textbf{{{fmt(hl.Boundary_IoU_pct)}}} & \textbf{{{fmt(hl.mIoU_pct-lora.mIoU_pct)}}} & \textbf{{{fmt(hl.Boundary_IoU_pct-lora.Boundary_IoU_pct)}}} {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    lines += [
        "\\begin{table}[H]",
        "\\caption{Paired Image-Level Analysis After Excluding the Diagnostic Pilot Subset}",
        "\\label{tab:excluding_pilot_paired}",
        "\\centering",
        "\\small",
        "\\begin{tabular}{l c c c c}",
        "\\toprule",
        rf"\textbf{{Metric}} & \textbf{{Mean gain (pp)}} & \textbf{{Median gain (pp)}} & \textbf{{95\% CI (pp)}} & \textbf{{Image win rate}} {LB}",
        "\\midrule",
    ]
    for _, row in paired.iterrows():
        lines.append(rf"{row['metric']} & {fmt(row['mean_gain_pp'])} & {fmt(row['median_gain_pp'])} & [{fmt(row['ci_low_pp'])}, {fmt(row['ci_high_pp'])}] & {fmt(row['win_rate']*100)}\\% {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    out.write_text("\n".join(lines), encoding="utf-8")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--per_image_csv", required=True, type=Path)
    ap.add_argument("--pilot_manifest", type=Path, default=None)
    ap.add_argument("--out_dir", required=True, type=Path)
    ap.add_argument("--lora_name", default=DEFAULT_LORA)
    ap.add_argument("--hl_name", default=DEFAULT_HL)
    ap.add_argument("--n_boot", type=int, default=2000)
    args = ap.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(args.per_image_csv)
    required = {"image_name", "region_prefix", "seed", "model", *METRICS}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")
    pilot_names = load_pilot_names(args.pilot_manifest)
    before_images = int(df["image_name"].nunique())
    df_eval = df[~df["image_name"].isin(pilot_names)].copy() if pilot_names else df.copy()
    after_images = int(df_eval["image_name"].nunique())
    if df_eval.empty:
        raise ValueError("No rows remain after filtering. Check pilot_manifest names.")
    per_seed = df_eval.groupby(["seed", "model"], as_index=False)[METRICS].mean().rename(columns={m:f"{m}_pct" for m in METRICS})
    for m in METRICS:
        per_seed[f"{m}_pct"] *= 100
    per_seed.to_csv(args.out_dir / "per_seed_metrics.csv", index=False)
    avg = df_eval.groupby(["image_name", "region_prefix", "model"], as_index=False)[METRICS].mean()
    paired_rows = []
    for metric in METRICS:
        pivot = avg.pivot_table(index=["image_name", "region_prefix"], columns="model", values=metric)
        if args.lora_name not in pivot.columns or args.hl_name not in pivot.columns:
            raise ValueError(f"Expected model names not found: {list(pivot.columns)}")
        diff = (pivot[args.hl_name] - pivot[args.lora_name]).dropna().to_numpy() * 100
        lo, hi = bootstrap_ci(diff, n_boot=args.n_boot)
        paired_rows.append({"metric":"Boundary IoU" if metric=="Boundary_IoU" else metric, "mean_gain_pp":diff.mean(), "median_gain_pp":np.median(diff), "ci_low_pp":lo, "ci_high_pp":hi, "win_rate":float((diff>0).mean())})
    paired = pd.DataFrame(paired_rows)
    paired.to_csv(args.out_dir / "paired_image_analysis.csv", index=False)
    region = df_eval.groupby(["region_prefix", "model"], as_index=False)[METRICS].mean().rename(columns={m:f"{m}_pct" for m in METRICS})
    for m in METRICS:
        region[f"{m}_pct"] *= 100
    region.to_csv(args.out_dir / "region_metrics.csv", index=False)
    summary = {"input_csv":str(args.per_image_csv), "pilot_manifest":str(args.pilot_manifest) if args.pilot_manifest else None, "pilot_images_loaded":len(pilot_names), "unique_images_before_filter":before_images, "unique_images_after_filter":after_images, "rows_after_filter":int(len(df_eval)), "per_seed_mean":per_seed.to_dict(orient="records"), "paired_image_analysis":paired.to_dict(orient="records"), "region_metrics":region.to_dict(orient="records")}
    (args.out_dir / "aggregate_metrics.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    make_latex_tables(per_seed, paired, args.out_dir / "latex_tables.tex")
    print(json.dumps({"unique_images_before_filter": before_images, "unique_images_after_filter": after_images, "pilot_images_loaded": len(pilot_names), "out_dir": str(args.out_dir)}, indent=2))
if __name__ == "__main__":
    main()
